name: CI

on: [push]

jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest

    env:
      GEMFILE_RUBY_VERSION: 3.1.2
      # Rails verifies the time zone in DB is the same as the time zone of the Rails app

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          # ruby-version: 2.7.2
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
        env:
          BUNDLE_GITHUB__COM: ${{ secrets.RUBY_GEM_BUNDLE_TOKEN }}
          BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.SIDEKIQ_ENTERPRISE_TOKEN }}
      
      - name: install dependencies 
        run: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - name: Run tests
        run: |
          mkdir /tmp/test-results

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress 
        

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: test-results
          path: /tmp/test-results
